### ISSUE TITLE
Dockerization of the project

### ISSUE THREAD

**Issue by olekstomek** [kacper1236/awantura-o-kase#1]
Have you thought about making it easy to run your application from Docker containers?

**Comment by kacper1236** [comment]
I only want to learn django (it's so bad idea) and in next time, I rewrite it to something better. And why should I use Docer for this project?

**Comment by olekstomek** [comment]
Okay. Docker allows you to run your project without any additional configuration (for example I don't have Python and Node.js installed locally on my system). Docker allows to run project without any system configuration effort, you just need to run a container which has all the configuration in it.

**Comment by olekstomek** [comment]
I was ale to run this project using Docker:
![aok](https://github.com/user-attachments/assets/aa07af98-d47c-46da-b159-82847370f5b0)
Put to `awantura_o_kase` catalog:
- `docker-compose.yml`:
```
version: '3.10'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/awantura_o_kase
      - .:/stream_overlay
    ports:
      - "8000:8000"
```

- `Dockerfile`:
```
FROM python:3.10

WORKDIR /awantura_o_kase

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
```
- `requirements.txt`:
```
Django
django-cors-headers
```
and run `docker-compose up -d`.

@kacper1236 just to be sure, there is no way to use this project to game yet? I mean that features are not implemented?
